spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cities
    username: postgres_user_city
    password: super_password
  flyway:
    enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true